-- ============================================================
-- AjQuiz Seed — All 114 Quran Surahs
-- Run this AFTER schema.sql
-- ============================================================

insert into quran_surahs (number, name_arabic, name_english, name_meaning, revelation_type, verse_count) values
  (1,   'ٱلْفَاتِحَة',       'Al-Fatihah',       'The Opening',              'Meccan',   7),
  (2,   'ٱلْبَقَرَة',        'Al-Baqarah',       'The Cow',                  'Medinan',  286),
  (3,   'آلِ عِمْرَان',      'Ali ''Imran',      'Family of Imran',          'Medinan',  200),
  (4,   'ٱلنِّسَاء',         'An-Nisa',          'The Women',                'Medinan',  176),
  (5,   'ٱلْمَائِدَة',       'Al-Ma''idah',      'The Table Spread',         'Medinan',  120),
  (6,   'ٱلْأَنْعَام',       'Al-An''am',        'The Cattle',               'Meccan',   165),
  (7,   'ٱلْأَعْرَاف',       'Al-A''raf',        'The Heights',              'Meccan',   206),
  (8,   'ٱلْأَنْفَال',       'Al-Anfal',         'The Spoils of War',        'Medinan',  75),
  (9,   'ٱلتَّوْبَة',        'At-Tawbah',        'The Repentance',           'Medinan',  129),
  (10,  'يُونُس',            'Yunus',            'Jonah',                    'Meccan',   109),
  (11,  'هُود',              'Hud',              'Hud',                      'Meccan',   123),
  (12,  'يُوسُف',            'Yusuf',            'Joseph',                   'Meccan',   111),
  (13,  'ٱلرَّعْد',          'Ar-Ra''d',         'The Thunder',              'Medinan',  43),
  (14,  'إِبْرَاهِيم',       'Ibrahim',          'Abraham',                  'Meccan',   52),
  (15,  'ٱلْحِجْر',          'Al-Hijr',          'The Rocky Tract',          'Meccan',   99),
  (16,  'ٱلنَّحْل',          'An-Nahl',          'The Bee',                  'Meccan',   128),
  (17,  'ٱلْإِسْرَاء',       'Al-Isra',          'The Night Journey',        'Meccan',   111),
  (18,  'ٱلْكَهْف',          'Al-Kahf',          'The Cave',                 'Meccan',   110),
  (19,  'مَرْيَم',           'Maryam',           'Mary',                     'Meccan',   98),
  (20,  'طه',                'Ta-Ha',            'Ta-Ha',                    'Meccan',   135),
  (21,  'ٱلْأَنْبِيَاء',     'Al-Anbiya',        'The Prophets',             'Meccan',   112),
  (22,  'ٱلْحَج',            'Al-Hajj',          'The Pilgrimage',           'Medinan',  78),
  (23,  'ٱلْمُؤْمِنُون',     'Al-Mu''minun',     'The Believers',            'Meccan',   118),
  (24,  'ٱلنُّور',           'An-Nur',           'The Light',                'Medinan',  64),
  (25,  'ٱلْفُرْقَان',       'Al-Furqan',        'The Criterion',            'Meccan',   77),
  (26,  'ٱلشُّعَرَاء',       'Ash-Shu''ara',     'The Poets',                'Meccan',   227),
  (27,  'ٱلنَّمْل',          'An-Naml',          'The Ant',                  'Meccan',   93),
  (28,  'ٱلْقَصَص',          'Al-Qasas',         'The Stories',              'Meccan',   88),
  (29,  'ٱلْعَنْكَبُوت',     'Al-''Ankabut',     'The Spider',               'Meccan',   69),
  (30,  'ٱلرُّوم',           'Ar-Rum',           'The Romans',               'Meccan',   60),
  (31,  'لُقْمَان',          'Luqman',           'Luqman',                   'Meccan',   34),
  (32,  'ٱلسَّجْدَة',        'As-Sajdah',        'The Prostration',          'Meccan',   30),
  (33,  'ٱلْأَحْزَاب',       'Al-Ahzab',         'The Combined Forces',      'Medinan',  73),
  (34,  'سَبَأ',             'Saba',             'Sheba',                    'Meccan',   54),
  (35,  'فَاطِر',            'Fatir',            'Originator',               'Meccan',   45),
  (36,  'يس',                'Ya-Sin',           'Ya Sin',                   'Meccan',   83),
  (37,  'ٱلصَّافَّات',       'As-Saffat',        'Those Ranged in Ranks',    'Meccan',   182),
  (38,  'ص',                 'Sad',              'The Letter Sad',           'Meccan',   88),
  (39,  'ٱلزُّمَر',          'Az-Zumar',         'The Groups',               'Meccan',   75),
  (40,  'غَافِر',            'Ghafir',           'The Forgiver',             'Meccan',   85),
  (41,  'فُصِّلَت',          'Fussilat',         'Explained in Detail',      'Meccan',   54),
  (42,  'ٱلشُّورَىٰ',        'Ash-Shuraa',       'The Consultation',         'Meccan',   53),
  (43,  'ٱلْزُّخْرُف',       'Az-Zukhruf',       'The Gold Adornments',      'Meccan',   89),
  (44,  'ٱلدُّخَان',         'Ad-Dukhan',        'The Smoke',                'Meccan',   59),
  (45,  'ٱلْجَاثِيَة',       'Al-Jathiyah',      'The Crouching',            'Meccan',   37),
  (46,  'ٱلْأَحْقَاف',       'Al-Ahqaf',         'The Wind-Curved Sandhills','Meccan',   35),
  (47,  'مُحَمَّد',          'Muhammad',         'Muhammad',                 'Medinan',  38),
  (48,  'ٱلْفَتْح',          'Al-Fath',          'The Victory',              'Medinan',  29),
  (49,  'ٱلْحُجُرَات',       'Al-Hujurat',       'The Rooms',                'Medinan',  18),
  (50,  'ق',                 'Qaf',              'The Letter Qaf',           'Meccan',   45),
  (51,  'ٱلذَّارِيَات',      'Adh-Dhariyat',     'The Winnowing Winds',      'Meccan',   60),
  (52,  'ٱلطُّور',           'At-Tur',           'The Mount',                'Meccan',   49),
  (53,  'ٱلنَّجْم',          'An-Najm',          'The Star',                 'Meccan',   62),
  (54,  'ٱلْقَمَر',          'Al-Qamar',         'The Moon',                 'Meccan',   55),
  (55,  'ٱلرَّحْمَٰن',       'Ar-Rahman',        'The Beneficent',           'Medinan',  78),
  (56,  'ٱلْوَاقِعَة',       'Al-Waqi''ah',      'The Inevitable',           'Meccan',   96),
  (57,  'ٱلْحَدِيد',         'Al-Hadid',         'The Iron',                 'Medinan',  29),
  (58,  'ٱلْمُجَادِلَة',     'Al-Mujadila',      'The Pleading Woman',       'Medinan',  22),
  (59,  'ٱلْحَشْر',          'Al-Hashr',         'The Exile',                'Medinan',  24),
  (60,  'ٱلْمُمْتَحَنَة',    'Al-Mumtahanah',    'She That is to be Examined','Medinan', 13),
  (61,  'ٱلصَّف',            'As-Saf',           'The Ranks',                'Medinan',  14),
  (62,  'ٱلْجُمُعَة',        'Al-Jumu''ah',      'The Congregation',         'Medinan',  11),
  (63,  'ٱلْمُنَافِقُون',    'Al-Munafiqun',     'The Hypocrites',           'Medinan',  11),
  (64,  'ٱلتَّغَابُن',       'At-Taghabun',      'The Mutual Disillusion',   'Medinan',  18),
  (65,  'ٱلطَّلَاق',         'At-Talaq',         'The Divorce',              'Medinan',  12),
  (66,  'ٱلتَّحْرِيم',       'At-Tahrim',        'The Prohibition',          'Medinan',  12),
  (67,  'ٱلْمُلْك',          'Al-Mulk',          'The Sovereignty',          'Meccan',   30),
  (68,  'ٱلْقَلَم',          'Al-Qalam',         'The Pen',                  'Meccan',   52),
  (69,  'ٱلْحَاقَّة',        'Al-Haqqah',        'The Reality',              'Meccan',   52),
  (70,  'ٱلْمَعَارِج',       'Al-Ma''arij',      'The Ascending Stairways',  'Meccan',   44),
  (71,  'نُوح',              'Nuh',              'Noah',                     'Meccan',   28),
  (72,  'ٱلْجِن',            'Al-Jinn',          'The Jinn',                 'Meccan',   28),
  (73,  'ٱلْمُزَّمِّل',      'Al-Muzzammil',     'The Enshrouded One',       'Meccan',   20),
  (74,  'ٱلْمُدَّثِّر',      'Al-Muddaththir',   'The Cloaked One',          'Meccan',   56),
  (75,  'ٱلْقِيَامَة',       'Al-Qiyamah',       'The Resurrection',         'Meccan',   40),
  (76,  'ٱلْإِنسَان',        'Al-Insan',         'The Man',                  'Medinan',  31),
  (77,  'ٱلْمُرْسَلَات',     'Al-Mursalat',      'The Emissaries',           'Meccan',   50),
  (78,  'ٱلنَّبَأ',          'An-Naba',          'The Announcement',         'Meccan',   40),
  (79,  'ٱلنَّازِعَات',      'An-Nazi''at',      'Those Who Drag Forth',     'Meccan',   46),
  (80,  'عَبَسَ',            'Abasa',            'He Frowned',               'Meccan',   42),
  (81,  'ٱلتَّكْوِير',       'At-Takwir',        'The Overthrowing',         'Meccan',   29),
  (82,  'ٱلْإِنْفِطَار',     'Al-Infitar',       'The Cleaving',             'Meccan',   19),
  (83,  'ٱلْمُطَفِّفِين',    'Al-Mutaffifin',    'The Defrauding',           'Meccan',   36),
  (84,  'ٱلْإِنْشِقَاق',     'Al-Inshiqaq',      'The Sundering',            'Meccan',   25),
  (85,  'ٱلْبُرُوج',         'Al-Buruj',         'The Mansions of the Stars','Meccan',   22),
  (86,  'ٱلطَّارِق',         'At-Tariq',         'The Morning Star',         'Meccan',   17),
  (87,  'ٱلْأَعْلَىٰ',       'Al-A''la',         'The Most High',            'Meccan',   19),
  (88,  'ٱلْغَاشِيَة',       'Al-Ghashiyah',     'The Overwhelming',         'Meccan',   26),
  (89,  'ٱلْفَجْر',          'Al-Fajr',          'The Dawn',                 'Meccan',   30),
  (90,  'ٱلْبَلَد',          'Al-Balad',         'The City',                 'Meccan',   20),
  (91,  'ٱلشَّمْس',          'Ash-Shams',        'The Sun',                  'Meccan',   15),
  (92,  'ٱللَّيْل',          'Al-Layl',          'The Night',                'Meccan',   21),
  (93,  'ٱلضُّحَىٰ',         'Ad-Duha',          'The Morning Hours',        'Meccan',   11),
  (94,  'ٱلشَّرْح',          'Ash-Sharh',        'The Relief',               'Meccan',   8),
  (95,  'ٱلتِّين',           'At-Tin',           'The Fig',                  'Meccan',   8),
  (96,  'ٱلْعَلَق',          'Al-Alaq',          'The Clot',                 'Meccan',   19),
  (97,  'ٱلْقَدْر',          'Al-Qadr',          'The Power',                'Meccan',   5),
  (98,  'ٱلْبَيِّنَة',       'Al-Bayyinah',      'The Clear Proof',          'Medinan',  8),
  (99,  'ٱلزَّلْزَلَة',      'Az-Zalzalah',      'The Earthquake',           'Medinan',  8),
  (100, 'ٱلْعَادِيَات',      'Al-''Adiyat',      'The Courser',              'Meccan',   11),
  (101, 'ٱلْقَارِعَة',       'Al-Qari''ah',      'The Calamity',             'Meccan',   11),
  (102, 'ٱلتَّكَاثُر',       'At-Takathur',      'The Rivalry in World Increase','Meccan',8),
  (103, 'ٱلْعَصْر',          'Al-''Asr',         'The Declining Day',        'Meccan',   3),
  (104, 'ٱلْهُمَزَة',        'Al-Humazah',       'The Traducer',             'Meccan',   9),
  (105, 'ٱلْفِيل',           'Al-Fil',           'The Elephant',             'Meccan',   5),
  (106, 'قُرَيْش',           'Quraysh',          'Quraysh',                  'Meccan',   4),
  (107, 'ٱلْمَاعُون',        'Al-Ma''un',        'The Small Kindnesses',     'Meccan',   7),
  (108, 'ٱلْكَوْثَر',        'Al-Kawthar',       'The Abundance',            'Meccan',   3),
  (109, 'ٱلْكَافِرُون',      'Al-Kafirun',       'The Disbelievers',         'Meccan',   6),
  (110, 'ٱلنَّصْر',          'An-Nasr',          'The Divine Support',       'Medinan',  3),
  (111, 'ٱلْمَسَد',          'Al-Masad',         'The Palm Fibre',           'Meccan',   5),
  (112, 'ٱلْإِخْلَاص',       'Al-Ikhlas',        'The Sincerity',            'Meccan',   4),
  (113, 'ٱلْفَلَق',          'Al-Falaq',         'The Daybreak',             'Meccan',   5),
  (114, 'ٱلنَّاس',           'An-Nas',           'The Mankind',              'Meccan',   6)
on conflict (number) do nothing;


create policy "Public read quran_surahs"
  on quran_surahs for select
  using (true);
